export enum StakingTypes {
  SET_STAKING_AMOUNT = "stakingStore/setStakingAmount",
  SET_TX_ID = "stakingStore/setTxId",
  SET_STAKING_ACCOUNTS = "stakingStore/setStakingAccounts",
  SET_DEACTIVATING_STAKE = "stakingStore/setDeactivatingStake",
  UPDATE_VALIDATOR_DATA = "stakingStore/updateValidatorData",
  UPDATE_STAKING_DATA = "stakingStore/updateStakingData",
  UPDATE_LOADING_STATE = "stakingStore/updateLoadingState",
  EMPTY_PORTFOLIO_STATE = "stakingStore/emptyPortfolio",
  SET_ERROR_STATE = "stakingStore/setErrorState",
  
  CREATE_STAKE_ACTION = "stakingStore/createStakeAction",
  START_STAKE_ACTION = "stakingStore/startStakeAction",
  SET_DEACTIVATING_STAKE_ACTION = "stakingStore/setDeactivatingStakeAction",
  START_DEACTIVATING_ACTION = "stakingStore/startDeactivateStakeAction",
  SET_WITHDRAW_STAKE_ACTION = "stakingStore/setWithdrawStakeAction",
  DEACTIVATE_STAKE_ACTION = "stakingStore/deactivateStakeAction",
  LOAD_STAKING_ACCOUNTS_ACTION = "stakingStore/loadStakingAccounts",
  WITHDRAW_STAKE_ACTION = "stakingStore/withdrawStakeAction",
  START_WITHDRAW_ACTION = "stakingStore/startWithdrawStakeAction",
  UPDATE_VALIDATOR_ACTION = "stakingStore/updateValidatorAction",
  UPDATE_STAKING_ACTION = "stakingStore/updateStakingAction",
  EMPTY_STAKING_ACCOUNTS_ACTION = "stakingStore/emptyStakingAccountsAction",
  
  STAKING_AMOUNT_GETTER = "stakingStore/getStakingAmount",
  TX_ID_GETTER = "stakingStore/getStakingTxID",
  DEACTIVATING_STAKE_GETTER = "stakingStore/getDeactivatingStake",
  DEACTIVATING_DATA_GETTER = "stakingStore/getDeactivatingData",
  PORTFOLIO_GETTER = "stakingStore/getPortfolio",
  PORTFOLIO_BY_CHAIN_GETTER = "stakingStore/getPortfolioByChain",
  WITHDRAW_STAKE_GETTER = "stakingStore/getWithdrawStake",
  WITHDRAW_DATA_GETTER = "stakingStore/getWithdrawData",
  STAKING_ITEMS_GETTER = "stakingStore/getStakingItems",
  VALIDATORS_GETTER = "stakingStore/getValidators",
  IS_LOADING_GETTER = "stakingStore/getIsLoading",
  IS_STAKING_LOADING_GETTER = "stakingStore/getIsStakingLoading",
  STAKING_DATA_GETTER = "stakingStore/getStakingData",
  STAKING_FEE_GETTER = "stakingStore/getStakingFee",
  DEACTIVATING_FEE_GETTER = "stakingStore/getDeactivatingFee",
  WITHDRAW_FEE_GETTER = "stakingStore/getWithdrawFee",
  ERROR_GETTER = "stakingStore/getError",
}
